package com.example.demo_data_API.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * The Customer entity represents a customer record in the database.
 * This entity is mapped to the "CUSTOMERS" table.
 */
@Entity
@Table(name = "CUSTOMERS")
public class Customer {

	/**
     * The unique identifier for the customer.
     * It is automatically generated by the database.
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	 /**
     * The name of the customer.
     * This field is mapped to the "CUSTOMER_NAME" column in the "CUSTOMERS" table.
     */
	@Column(name = "CUSTOMER_NAME")
	private String name;

	/**
     * The email address of the customer.
     */
	private String email;

	/**
     * The password for the customer's account.
     */
	private String password;


	/**
     * Setters and getters to access the private variables
     */
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;

	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
}
